"""Deciding what caused a cache miss, and what is safe to advise about it.

The rule this module exists to enforce: never name a file that could not have
caused the miss. A confidently wrong answer is worse than no answer.
"""

import re
from pathlib import Path

# Files that are regenerable or churn every commit: near-always safe to ignore.
NOISE = [
    (".git/", ".git/", "changes on every commit"),
    ("node_modules/", "node_modules/", "reinstallable from lockfile"),
    ("__pycache__/", "**/__pycache__/", "regenerated by Python"),
    (".venv/", ".venv/", "local virtualenv"),
    ("venv/", "venv/", "local virtualenv"),
    ("dist/", "dist/", "build output"),
    ("build/", "build/", "build output"),
    ("target/", "target/", "build output"),
    (".pytest_cache/", ".pytest_cache/", "test cache"),
    (".mypy_cache/", ".mypy_cache/", "type-check cache"),
]

# Tools that read git metadata at build time. Excluding .git/ from a project
# using any of these does not merely lose caching - it breaks the build.
# Learned by breaking psf/black's build with this tool's own advice.
GIT_NEEDED = re.compile(
    r"hatch[-_]vcs|setuptools[-_]scm|versioningit|dunamai|"
    r"git\s+describe|git\s+rev-parse|GitVersion|gitdescribe",
    re.I,
)


def copy_sources(instr):
    """Source paths of a COPY/ADD, or None if this isn't one.

    `COPY requirements.txt .` must only ever be blamed on requirements.txt.
    Blaming unrelated files is the fastest way to lose a user's trust.
    """
    m = re.match(r"^(?:COPY|ADD)\s+(.*)$", instr, re.I)
    if not m:
        return None
    args = [a for a in m.group(1).split() if not a.startswith("--")]
    return args[:-1]  # last arg is the destination


def blame(changed, sources):
    """Narrow the changed-file list to what this instruction actually copies."""
    if not sources or any(s in (".", "./") for s in sources):
        return changed
    out = []
    for path in changed:
        for s in sources:
            s = s.strip("./")
            if path == s or path.startswith(s + "/"):
                out.append(path)
                break
    return out


def previous_instr(miss, old_steps):
    """What this step's command said last time, if it has since changed.

    BuildKit resolves ARG and ENV substitutions before naming a vertex, so a
    changed build arg shows up here as changed instruction text - which is the
    difference between "something changed" and naming what it was.
    """
    for s in old_steps or ():
        if s.get("stage") == miss["stage"] and s.get("idx") == miss["idx"]:
            return s.get("instr") if s.get("instr") != miss["instr"] else None
    return None


def build_needs_git(context):
    """Filename that shows this build reads git metadata, or None."""
    for name in ("pyproject.toml", "setup.py", "setup.cfg", "Dockerfile",
                 "package.json", "build.gradle"):
        try:
            text = (Path(context) / name).read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        if GIT_NEEDED.search(text):
            return name
    return None


def noise_hits(paths):
    """(pattern, reason, count) for regenerable junk among the changed files."""
    hits = []
    for prefix, pattern, reason in NOISE:
        n = sum(1 for p in paths
                if p == prefix.rstrip("/") or f"/{prefix}" in f"/{p}")
        if n:
            hits.append((pattern, reason, n))
    return hits
