"""whycache - explain why the Docker build cache broke.

Usage:  python whycache.py [context-dir] [-- extra docker build args]
"""

import json
import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path

from .manifest import build_manifest, diff, load_state, save_state

# Real build steps. Multi-stage builds prefix the stage name, so both of these
# must match or the tool silently sees zero steps and calls a 5-minute build
# "fully cached":
#   [4/5] RUN pip install ...
#   [builder 3/7] RUN apt update ...
#   [stage-1 2/3] COPY --from=builder ...
RE_STEP = re.compile(r"^\[(?:([^\]\s]+)\s+)?(\d+)/(\d+)\]\s*(.*)$")

# Files that are regenerable or churn every commit: near-always safe to ignore.
NOISE = [
    (".git/", ".git/", "changes on every commit"),
    ("node_modules/", "node_modules/", "reinstallable from lockfile"),
    ("__pycache__/", "**/__pycache__/", "regenerated by Python"),
    (".venv/", ".venv/", "local virtualenv"),
    ("venv/", "venv/", "local virtualenv"),
    ("dist/", "dist/", "build output"),
    ("build/", "build/", "build output"),
    ("target/", "target/", "build output"),
    (".pytest_cache/", ".pytest_cache/", "test cache"),
    (".mypy_cache/", ".mypy_cache/", "type-check cache"),
]


def _encodable(text):
    """Windows consoles default to cp1252 and blow up on box-drawing glyphs."""
    try:
        text.encode(sys.stdout.encoding or "ascii")
        return True
    except (UnicodeEncodeError, LookupError):
        return False


HIT, MISS = ("✓", "✗") if _encodable("✓✗") else ("OK", "X")


def _ts(s):
    """BuildKit mixes UTC 'Z' and local offsets, with nanosecond precision."""
    s = re.sub(r"(\.\d{6})\d+", r"\1", s)
    return datetime.fromisoformat(s.replace("Z", "+00:00"))


def run_build(context, extra=()):
    """Run the build, return (returncode, vertexes-by-digest, raw output)."""
    cmd = ["docker", "build", "--progress=rawjson", *extra, "."]
    p = subprocess.run(cmd, cwd=context, capture_output=True, text=True)
    out = p.stdout + p.stderr

    vertexes = {}
    for line in out.splitlines():
        line = line.strip()
        if not line.startswith("{"):
            continue
        try:
            obj = json.loads(line)
        except json.JSONDecodeError:
            continue
        for v in obj.get("vertexes", []):
            # vertexes are re-emitted as they progress; last state wins
            vertexes.setdefault(v["digest"], {}).update(v)
    return p.returncode, vertexes, out


def steps_of(vertexes):
    """Real build steps, in execution order.

    BuildKit emits vertexes in *completion* order, and that order changes
    between runs (Phase 0 probe), so output order is never trustworthy. The
    [i/n] index only orders steps *within* one stage, which is not enough for
    multi-stage builds — so order by the reported start time, which is the
    real thing.
    """
    steps = []
    for v in vertexes.values():
        m = RE_STEP.match(v.get("name", ""))
        if not m:
            continue
        started = v.get("started")
        secs = None
        if started and v.get("completed"):
            secs = (_ts(v["completed"]) - _ts(started)).total_seconds()
        steps.append({
            "stage": m.group(1),
            "idx": int(m.group(2)),
            "instr": m.group(4),
            "cached": bool(v.get("cached")),
            "secs": secs,
            "started": _ts(started) if started else None,
        })
    # steps with no start time sort last; they are the ones we know least about
    return sorted(steps, key=lambda s: (s["started"] is None, s["started"], s["idx"]))


def real_steps(steps):
    """Steps that can meaningfully miss.

    FROM is excluded: base-image resolution reports DONE and never CACHED, so
    it always looks like a miss.

    ponytail: this also hides a genuinely changed base image. Phase 2 should
    compare the resolved base digest across runs to catch that separately.
    """
    return [s for s in steps if not s["instr"].upper().startswith("FROM ")]


def first_miss(steps):
    """Earliest non-cached step. None => fully cached."""
    for s in real_steps(steps):
        if not s["cached"]:
            return s
    return None


def copy_sources(instr):
    """Source paths of a COPY/ADD, or None if this isn't one.

    `COPY requirements.txt .` must only ever be blamed on requirements.txt.
    Blaming unrelated files is the fastest way to lose a user's trust.
    """
    m = re.match(r"^(?:COPY|ADD)\s+(.*)$", instr, re.I)
    if not m:
        return None
    args = [a for a in m.group(1).split() if not a.startswith("--")]
    return args[:-1]  # last arg is the destination


def previous_instr(miss, old_steps):
    """What this step's command said last time, if it has since changed.

    BuildKit resolves ARG and ENV substitutions before naming a vertex, so a
    changed build arg shows up here as changed instruction text — which is the
    difference between "something changed" and naming what it was.
    """
    for s in old_steps or ():
        if s.get("stage") == miss["stage"] and s.get("idx") == miss["idx"]:
            return s.get("instr") if s.get("instr") != miss["instr"] else None
    return None


def blame(changed, sources):
    """Narrow the changed-file list to what this instruction actually copies."""
    if not sources or any(s in (".", "./") for s in sources):
        return changed
    out = []
    for path in changed:
        for s in sources:
            s = s.strip("./")
            if path == s or path.startswith(s + "/"):
                out.append(path)
                break
    return out


# Tools that read git metadata at build time. Excluding .git/ from a project
# using any of these does not merely lose caching — it breaks the build.
# Learned by breaking psf/black's build with this tool's own advice.
GIT_NEEDED = re.compile(
    r"hatch[-_]vcs|setuptools[-_]scm|versioningit|dunamai|"
    r"git\s+describe|git\s+rev-parse|GitVersion|gitdescribe",
    re.I,
)


def build_needs_git(context):
    """Filename that shows this build reads git metadata, or None."""
    for name in ("pyproject.toml", "setup.py", "setup.cfg", "Dockerfile",
                 "package.json", "build.gradle"):
        try:
            text = (Path(context) / name).read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        if GIT_NEEDED.search(text):
            return name
    return None


def noise_hits(paths):
    """(pattern, reason, count) for regenerable junk among the changed files."""
    hits = []
    for prefix, pattern, reason in NOISE:
        n = sum(1 for p in paths
                if p == prefix.rstrip("/") or f"/{prefix}" in f"/{p}")
        if n:
            hits.append((pattern, reason, n))
    return hits


def human(secs):
    if secs < 60:
        return f"{secs:.1f}s"
    return f"{int(secs // 60)}m{int(secs % 60):02d}s"


def report(steps, miss, changed, cold, have_baseline, git_needed=None,
           prev_instr=None):
    # Parsing nothing must never be reported as success. A silent zero here is
    # how the tool once called a 5-minute multi-stage build "fully cached".
    if not steps:
        print("\n? Could not read any build steps from Docker's output.")
        print("  Not reporting a result rather than guessing at one.\n")
        return

    total = sum(s["secs"] or 0 for s in steps)

    if miss is None:
        print(f"\n{HIT} Fully cached. Build took {human(total)}.\n")
        return

    # Everything downstream of a miss re-runs, and in a multi-stage build that
    # spans stages — so the wasted work is simply every step that re-ran.
    wasted = sum(s["secs"] or 0 for s in real_steps(steps) if not s["cached"])

    where = f"{miss['stage']} step {miss['idx']}" if miss["stage"] else f"step {miss['idx']}"
    print(f"\n{MISS} Cache broke at {where}:  {miss['instr'][:70]}\n")

    # Order matters. "Nothing was cached" is what an early miss looks like from
    # the outside — a miss at the first step leaves nothing downstream that
    # *could* be cached — so treating it as a cold cache up front suppresses the
    # real, known answer. Definite explanations first; cold cache only as the
    # fallback when nothing else explains it.
    if not have_baseline:
        print("  Baseline saved. Change something and run again to see the cause.\n")
        return

    if prev_instr:
        print("  Reason - the instruction itself changed since the last build:\n")
        print(f"    was:  {prev_instr[:66]}")
        print(f"    now:  {miss['instr'][:66]}")
        print("\n  A changed build arg or env var shows up here, because Docker")
        print("  substitutes them into the command before caching it.")
        print(f"\n  Cost - {human(wasted)} of this {human(total)} build.\n")
        return

    if not changed:
        if cold:
            print("  Cache was cold - nothing was cached, so no file is responsible.")
            print("  (Pruned cache, a fresh builder, or --no-cache.)\n")
        else:
            print("  No context file changed, and this step's command is unchanged.")
            print("  The cause is upstream of the build context - most likely a")
            print("  --build-arg, a --secret or --mount, or a moved base image tag.\n")
        return

    print(f"  Reason - {len(changed)} file(s) changed in the build context:\n")
    for p in changed[:12]:
        print(f"    {p}")
    if len(changed) > 12:
        print(f"    ... and {len(changed) - 12} more")

    print(f"\n  Cost - {human(wasted)} of this {human(total)} build.")

    hits = noise_hits(changed)
    safe = [h for h in hits if not (h[0] == ".git/" and git_needed)]
    risky = [h for h in hits if h[0] == ".git/" and git_needed]

    if safe:
        print("\n  Fix - add to .dockerignore:")
        for pattern, reason, n in safe:
            print(f"    {pattern:<22} ({reason}, {n} file(s))")
        print(f"\n  Saves ~{human(wasted)} per build.")

    for _, _, n in risky:
        print(f"\n  .git/ is breaking the cache ({n} file(s)), but do NOT ignore it:")
        print(f"    {git_needed} reads git metadata at build time, so excluding")
        print("    .git/ makes the build fail rather than just slow.")
        print("    Pass the version in as a build arg instead, or copy .git in a")
        print("    later stage so it stops invalidating the expensive steps.")
    print()


def main(argv):
    args = argv[1:]
    extra = []
    if "--" in args:
        i = args.index("--")
        args, extra = args[:i], args[i + 1:]
    context = Path(args[0] if args else ".").resolve()

    if not (context / "Dockerfile").exists():
        print(f"No Dockerfile in {context}", file=sys.stderr)
        return 2

    # Read the baseline before anything can overwrite it.
    old = load_state(context)
    have_baseline = old is not None

    new_manifest, new_stats = build_manifest(context, old)
    rc, vertexes, out = run_build(context, extra)

    # A failed build still caches every step that completed before the failure,
    # so Docker's cache moves forward even when the build does not. Skipping
    # the save here leaves our baseline behind Docker's, and the next run then
    # reports "no context file changed" for a context that really did change.
    steps = steps_of(vertexes)
    save_state(context, {"manifest": new_manifest, "stat": new_stats,
                         "steps": [{"stage": x["stage"], "idx": x["idx"],
                                    "instr": x["instr"]} for x in steps]})

    if rc != 0:
        print(out[-2000:], file=sys.stderr)
        print("\ndocker build failed - nothing to explain.", file=sys.stderr)
        return rc

    miss = first_miss(steps)

    # "nothing cached at all" is only a hint, never the first answer - see the
    # ordering note in report().
    # ponytail: tracking the builder id too would catch a switched builder that
    # still had some steps cached.
    real = real_steps(steps)
    cold = bool(real) and not any(s["cached"] for s in real)

    changed = []
    if miss and have_baseline:
        d = diff(old.get("manifest", {}), new_manifest)
        changed = blame(sorted(d["added"] + d["removed"] + d["changed"]),
                        copy_sources(miss["instr"]))

    report(steps, miss, changed, cold, have_baseline, build_needs_git(context),
           previous_instr(miss, (old or {}).get("steps")) if miss else None)
    return 0



def cli():
    """Console-script entry point."""
    sys.exit(main(sys.argv))
